export const RECEIVE_RECIPES = "RECIPES:RECEIVE_RECIPES";
export const RECEIVE_NEW_RECIPES = "RECIPES:RECEIVE_NEW_RECIPES";
export const RECIPES_ARE_LOADING = "RECIPES:RECIPES_ARE_LOADING";
export const SET_RECIPES_LIMIT = "RECIPES:SET_RECIPES_LIMIT";
