export const RECEIVE_RECIPE = "RECIPE_DETAIL:RECEIVE_RECIPE";
export const IS_RECIPE_LOADING = "RECIPE_DETAIL:IS_RECIPE_LOADING";
export const ERASE_RECIPE = "RECIPE_DETAIL:ERASE_RECIPE";
export const SET_RECIPE_SCORE = "RECIPE_DETAIL:SET_RECIPE_SCORE";
